version: '3'

services:
  database:
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    image: postgres:alpine
    network_mode: "host"

  api-template:
    depends_on:
      - database
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: api-template
    volumes:
      - ./:/usr/src/app:z
    network_mode: "host"
    restart: on-failure
    environment:
      # database > postgresql
      POSTGRESQL_HOST: localhost
      POSTGRESQL_PORT:  5432
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_DATABASE: postgres
      # app 
      APP_PREFIX: /v1
      APP_PORT: 9000
      # openapi
      OPENAPI_NAME: API template
      OPENAPI_DESCRIPTION: Model API for future applications
      OPENAPI_PREFIX: /docs
    command: sh -c "yarn typeorm:run-migration && yarn start:debug"